[package]
name = "underlay-auth-totp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base32 = "0.5"
hex = "0.4"
hmac = "0.12"
qrcode = "0.14"
rand = "0.10.1"
sha1 = "0.10"
sha2 = "0.10"
thiserror = "2"
underlay-auth = { path = "../underlay-auth" }
underlay-core = { path = "../underlay-core" }

[dev-dependencies]
chrono = { workspace = true }
