[package]
name = "underlay-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }
underlay-core = { path = "../underlay-core" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
