[package]
name = "underlay-email"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
smtp = ["lettre"]
ses = ["aws-sdk-sesv2", "underlay-aws"]
templates = ["tera"]

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7"] }

# SMTP adapter (optional)
lettre = { version = "0.11", features = ["tokio1-native-tls", "builder"], optional = true }

# AWS SES adapter (optional)
aws-sdk-sesv2 = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio", "sigv4a"], optional = true }
underlay-aws = { workspace = true, optional = true }

# Email templates (optional)
tera = { version = "1", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
