[package]
name = "underlay-auth-password"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
base64 = "0.22"
rand = "0.10.1"
serde = { workspace = true }
underlay-auth = { path = "../underlay-auth", features = ["hashing"] }
underlay-core = { path = "../underlay-core" }
underlay-ratelimit = { path = "../underlay-ratelimit" }
uuid = { workspace = true }
zxcvbn = "3"

underlay-http-client = { workspace = true, optional = true }
sha1 = { version = "0.10", optional = true }

[features]
hibp = ["underlay-http-client", "dep:sha1"]

[dev-dependencies]
chrono = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
