[package]
name = "underlay-auth-state"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = "2"
underlay-core = { path = "../underlay-core" }

[dev-dependencies]
tokio = { workspace = true }
