[package]
name = "underlay-validation-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Derive macro for underlay-validation"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }

[lints]
workspace = true
