// Generated by poodle-icons. Do not edit.
type IconNodes = [string, Record<string, string>][];

export const icons: Record<string, IconNodes> = {
  "calendar": [
    [
      "path",
      {
        "d": "M8 2v3"
      }
    ],
    [
      "path",
      {
        "d": "M16 2v3"
      }
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "3",
        "width": "18",
        "height": "18",
        "rx": "2"
      }
    ],
    [
      "path",
      {
        "d": "M3 9h18"
      }
    ]
  ],
  "circle-alert": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ],
    [
      "line",
      {
        "x1": "12",
        "x2": "12",
        "y1": "8",
        "y2": "12"
      }
    ],
    [
      "line",
      {
        "x1": "12",
        "x2": "12.01",
        "y1": "16",
        "y2": "16"
      }
    ]
  ],
  "list-checks": [
    [
      "path",
      {
        "d": "M13 5h8"
      }
    ],
    [
      "path",
      {
        "d": "M13 12h8"
      }
    ],
    [
      "path",
      {
        "d": "M13 19h8"
      }
    ],
    [
      "path",
      {
        "d": "m3 17 2 2 4-4"
      }
    ],
    [
      "path",
      {
        "d": "m3 7 2 2 4-4"
      }
    ]
  ],
  "lock": [
    [
      "rect",
      {
        "width": "18",
        "height": "11",
        "x": "3",
        "y": "11",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "path",
      {
        "d": "M7 11V7a5 5 0 0 1 10 0v4"
      }
    ]
  ]
};

export const calendar = icons["calendar"];
export const circleAlert = icons["circle-alert"];
export const listChecks = icons["list-checks"];
export const lock = icons["lock"];
